VERSION = "0.3.2"

DEBUG = False
VIEW_MODE = True

LOG_FILENAME = 'errors.log'

PLOT_STATS_OFFSET = 0.15

PLOT_TOP = 0.85

PLOT_LEFT = 0.05
PLOT_RIGHT = 0.95
PLOT_WIDTH = PLOT_RIGHT - PLOT_LEFT

PLOT_SINGLE_BOTTOM = 0.20
PLOT_SINGLE_HEIGHT = PLOT_TOP - PLOT_SINGLE_BOTTOM

PLOT_SINGLE_BASE_POSITION = [PLOT_LEFT, PLOT_SINGLE_BOTTOM, PLOT_WIDTH, PLOT_SINGLE_HEIGHT]  #l, b, w, h
PLOT_SINGLE_STATS_POSITION = [PLOT_LEFT, PLOT_SINGLE_BOTTOM+PLOT_STATS_OFFSET, PLOT_WIDTH, PLOT_SINGLE_HEIGHT-PLOT_STATS_OFFSET]

PLOT_MULTI_BOTTOM = 0.10
PLOT_MULTI_HEIGHT = PLOT_TOP - PLOT_MULTI_BOTTOM
PLOT_MULTI_POSITION = [PLOT_LEFT, PLOT_MULTI_BOTTOM, PLOT_WIDTH, PLOT_MULTI_HEIGHT]  #l, b, w, h

PLOT_STATS_BOTTOM = 0.17
PLOT_STATS_POSITION = [PLOT_LEFT, PLOT_STATS_BOTTOM, PLOT_WIDTH, PLOT_STATS_OFFSET]
